version: '3.3'
services:
  holigo-influencer-service:
    image: holigo/holigo-influencer-service:1.5.1
    ports:
      - 8131:8131
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
    logging:
      options:
        'max-size': '10m'
        'max-file': '5'